import './globals.css';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'my first NextJS app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={``}>
        <div>{children}</div>
        <ToastContainer position='top-center' autoClose={2000} />
      </body>
    </html>
  );
}
